### ISSUE TITLE
Hard-coded site id = 1

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-local_checkmarkreport#1]
https://github.com/academic-moodle-cooperation/moodle-local_checkmarkreport/blob/master/lib.php#L49 has hard-coded site id in `if (!$PAGE->course or $PAGE->course->id == 1)`.

Some sites may have the front site course with id != 1, the code like this should always check against the core constant `SITEID`.

**Comment by kaspot** [comment]
thanks - added to our todo list

**Comment by kaspot** [comment]
Should be fixed in the newest Moodle 2.8 version.
