### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-local_checkmarkreport#2]
**When in checkmark you have this, everything OK**
![imagem](https://user-images.githubusercontent.com/14828021/35971067-76901fd8-0cc4-11e8-83a3-c9199dbca727.png)

**But when you have THIS**
![imagem](https://user-images.githubusercontent.com/14828021/35971103-9c747ac8-0cc4-11e8-8abd-295651f04221.png)

**Look at warning**
![imagem](https://user-images.githubusercontent.com/14828021/35971207-1423f3d2-0cc5-11e8-8621-357a286043b4.png)

**Comment by dinism** [comment]
The S is for SUM!! 👍

**Comment by phager-at** [comment]
Hi dinism,

yes, the S is for SUM, maybe we'll replace it with an Σ in the near future - I currently don't remember why we favored the S in the past - we'll discuss that :)

Regarding the Notice, I'll file a ticket in our system and we'll fix that with the next minor release! Thanks for reporting the notice!

regards,
Philipp

**Comment by goggo24** [comment]
So now both the symbol "S" and the warning with scales is fixed => v.3.6.0.
Publication is coming soon ;)
